dbt_banks_info:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: dbt_job
      password: dbt_job
      port: 5432
      dbname: DBT
      schema: public